# Do not edit. Generated by the configure script.
{
  'target_defaults': {
    'cflags%': [],
    'default_configuration': 'Release',
    'defines': [],
    'include_dirs': [],
    'libraries': []
  },
  'variables': {
    'boost_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/boost/system/include'],
    'boost_ldflags%': ['-L/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/boost/system/lib'],
    'curl_static_libs%': [],
    'curl_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libcurl/system/include'],
    'curl_ldflags%': ['-L/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libcurl/system/lib', '-lcurl'],
    'glfw3_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/glfw/3.1/lib/libglfw3.a'],
    'glfw3_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/glfw/3.1/include'],
    'glfw3_ldflags%': ['-framework Cocoa', '-framework OpenGL', '-framework IOKit', '-framework CoreFoundation', '-framework CoreVideo'],
    'opengl_cflags%': [],
    'opengl_ldflags%': [],
    'png_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libpng/1.6.16/lib/libpng.a'],
    'png_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libpng/1.6.16/include/libpng16'],
    'png_ldflags%': ['-lz'],
    'jpeg_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/jpeg/v9a/lib/libjpeg.a'],
    'jpeg_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/jpeg/v9a/include'],
    'jpeg_ldflags%': [],
    'sqlite3_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/sqlite/3.8.8.1/lib/libsqlite3.a'],
    'sqlite3_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/sqlite/3.8.8.1/include'],
    'sqlite3_ldflags%': [],
    'uv_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libuv/0.10.28/lib/libuv.a'],
    'uv_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libuv/0.10.28/include'],
    'uv_ldflags%': ['-lpthread', '-ldl', '-framework CoreFoundation', '-framework CoreServices'],
    'zlib_static_libs%': [],
    'zlib_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/zlib/system/include'],
    'zlib_ldflags%': ['-L/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/zlib/system/lib', '-lz'],
    'nu_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/nunicode/1.5.1/lib/libnu.a'],
    'nu_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/nunicode/1.5.1/include'],
    'nu_ldflags%': [],
    'zip_static_libs%': ['/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libzip/0.11.2/lib/libzip.a'],
    'zip_cflags%': ['-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libzip/0.11.2/include', '-I/Users/mgdesign/Desktop/Stage/mapbox-gl-native/mason_packages/osx-10.10/libzip/0.11.2/lib/libzip/include'],
    'zip_ldflags%': ['-lz'],
  }
}

